// Full abuse contacts list
const abuseContacts = {
  "Enflick": { emails: ["abuse@enflick.com", "abuse@textnow.com"], url: "" },
  "TextNow": { emails: ["abuse@textnow.com", "abuse@enflick.com"], url: "" },
  "Google Voice": { emails: ["support@mybwc.zendesk.com"], url: "" },
  "Bandwidth": { emails: ["support@mybwc.zendesk.com", "voicesecurity@bandwidth.com"], url: "" },
  "Localphone 360 Networks SVR": { emails: ["dids@voxbeam.com"], url: "" },
  "MCImetro": { emails: ["security.issues@verizon.com", "abuse@verizon.com"], url: "" },
  "Verizon": { emails: ["abuse@verizon.com", "security.issues@verizon.com", "ResearchandCompliance@one.verizon.com", "robert.chirino@verizon.com"], url: "" },
  "Onvoy": { emails: ["regina.echols@inteliquent.com", "abuse@onvoy.com"], url: "" },
  "Peerless Network": { emails: ["report@peerlessnetwork.com", "CourtOrders@subsentio.com", "LELiaison@subsentio.com", "Abuse@subsentio.com", "trouble@peerlessnetwork.com"], url: "" },
  "T-Mobile": { emails: ["Abuse@t-mobile.com", "KeLevine@tracfone.com"], url: "" }
  "Twilio": { emails: ["stopspam@twilio.com", "support@twilio.zendesk.com"], url: "" },
  "VoxBeam": { emails: ["dids@voxbeam.com", "support@voxbeam.com"], url: "" },
  "MagicJack": { emails: ["ReportAbuse@magicjack.com"], url: "" },
  "YMAX": { emails: ["ReportAbuse@magicjack.com"], url: "" },
  "382 Communications": { emails: ["abuse@382com.com", "support@382com.com"], url: "" },
  "7G Network, Inc": { emails: ["abuse@zayo.com", "CanCustomerService@Allstream.com", "UScustomerservice@allstream.com", "support@allstream.com"], url: "" },
  "800.com": { emails: ["support@800.com", "ron@7gnetwork.net"], url: "" },
  "Advanced Telecom Solutions, LLC": { emails: ["support@turbobridge.com"], url: "" },
  "Aerialink/Geneseo (SVR)": { emails: ["support@mybwc.zendesk.com"], url: "" },
  "Airus": { emails: ["report@peerlessnetwork.com", "CourtOrders@subsentio.com", "LELiaison@subsentio.com", "Abuse@subsentio.com", "abuse@peerlessnetwork.com", "trouble@peerlessnetwork.com"], url: "" },
  "Alcazar Networks": { emails: ["johnc@alcazarnetworks.com", "cso@alcazarnetworks.com", "abuse@alcazarnetworks.com"], url: "" }
  "Allstream Inc.": { emails: ["abuse@zayo.com", "CanCustomerService@Allstream.com", "UScustomerservice@allstream.com", "support@allstream.com"], url: "" },
  "Ameritech Illinois": { emails: ["abuse@att.net"], url: "" },
  "AT&T": { emails: ["abuse@att.net"], url: "" },
  "Astound Broadband": { emails: ["customerservice@wavebroadband.com"], url: "" },
  "Bell Mobility Inc.": { emails: ["abuse@bell.ca"], url: "" },
  "Blitz Telecom": { emails: ["crm@blitztelus.com", "investigate@blitztelecomservices.com"], url: "" },
  "Brightlink Communications": { emails: ["noc@brightlink.com"], url: "" },
  "Broadview": { emails: ["fraudmailbox@windstream.com"], url: "" },
  "Broadvox": { emails: ["abuse@onvoy.com"], url: "https://www.inteliquent.com/contact-legal/report-abuse" },
  "Callture": { emails: ["support@callture.com"], url: "" },
  "Cavalier Telephone": { emails: ["Windstream.NetworkAbuse@Windstream.com"], url: "" },
  "CenturyLink": { emails: ["security.feedback@level3.com", "abuse@level3.com", "abuse@centurylink.com", "support@centurylink.com"], url: "" },
  "Chatr": { emails: ["officeofpresident@chatrmobile.com", "abuse@chatrmobile.com"], url: "" },
  "Cingular Wireless": { emails: ["customerservice@consumercellular.com", "support@consumercellular.com"], url: "" },
  "Core Communications": { emails: ["voipservice@coretel.net", "sales@coretel.net", "abuse@coretel.net", "service@coretel.net"], url: "" },
  "Coretel": { emails: ["voipservice@coretel.net", "sales@coretel.net", "abuse@coretel.net", "service@coretel.net"], url: "" },
  "CTSI, Inc": { emails: ["tammy@ctsioutsourcing.com"], url: "" }
  "Distributel": { emails: ["abuse@distributel.ca", "support@thinktel.ca", "info@distributel.ca", "sales@distributel.ca"], url: "" },
  "Excel Telecommunications": { emails: ["customercare@impacttelecom.com"], url: "" },
  "Exiant Communications": { emails: ["crm@blitztelus.com", "lnp@exiantcom.com"], url: "" },
  "Fibernetics": { emails: ["abuse@fibernetics.ca"], url: "http://www.fibernetics.ca/contact-us/" },
  "Flowroute Inc": { emails: ["subpoenas@flowroute.com", "Westcarrierfraudnotifications@west.com"], url: "" },
  "GoTextMe": { emails: ["abuse@go-text.me"], url: "" },
  "Grasshopper Group LLC": { emails: ["support-replies@logmein.com", "rich.trabucco@logmein.com", "noc@grasshopper.com", "dschiavone@grasshopper.com"], url: "" },
  "Hypercube Telcom": { emails: ["Westcarrierfraudnotifications@west.com"], url: "" },
  "IDT Corporation": { emails: ["gabe.sasso@idt.net"], url: "" },
  "Immediate Services, LLC": { emails: ["support@teli.net", "sales@teli.net", "abuse@teli.net"], url: "http://www.teli.net/contact/" },
  "Integrated Path Communications, LLC": { emails: ["customercare@iristel.com", "abuse@iristel.com", "support@iristel.com", "security@iristel.ca"], url: "" },
  "Inteliquent": { emails: ["regina.echols@inteliquent.com", "abuse@onvoy.com"], url: "https://www.inteliquent.com/contact-legal/report-abuse" },
  "ISP Telecom": { emails: ["sub-inquiry@isptelecom.net", "marianne@isptelecom.net"], url: "" },
  "KCINDUR Communications": { emails: ["kim@advancedwireless.us", "abuse@advancedwireless.us", "support@advancedwireless.us"], url: "" }
  "Level 3 Communications": { emails: ["security.feedback@level3.com", "abuse@level3.com"], url: "" },
  "Local Access LLC": { emails: ["subpoena@localaccessllc.com", "sales@localaccessllc.com", "report@peerlessnetwork.com"], url: "" },
  "Navigata": { emails: ["connections@navigata.ca", "sales@navigata.ca", "abuse@navigata.ca", "support@navigata.ca"], url: "" },
  "Neutral Tandem": { emails: ["regina.echols@inteliquent.com", "abuse@onvoy.com"], url: "https://www.inteliquent.com/contact-us/report-abuse" },
  "Nuwave Resporg": { emails: ["info@nuwave.com", "abuse@nuwave.com", "support@nuwave.com", "abuse@nuwaveresporg.com"], url: "" },
  "ONCALL Resporg": { emails: ["scleland@atlc.com", "support@atlc.zendesk.com"], url: "" },
  "Pacific Bell": { emails: ["abuse@att.net"], url: "" },
  "Paetec Communications": { emails: ["Windstream.NetworkAbuse@Windstream.com"], url: "" },
  "Plivo": { emails: ["abuse@plivo.com", "support@plivo.com"], url: "" },
  "Primus": { emails: ["customer.care@primustel.ca", "support@primustel.ca", "support@primus-wireless.ca"], url: "" },
  "Qwest": { emails: ["abuse@qwest.net"], url: "" },
  "RingCentral": { emails: ["fraudresponse@ringcentral.com", "Fraudalert@ringcentral.com"], url: "" },
  "Rogers Communications Partnership": { emails: ["abuse@rogers.com", "phishing@rogers.com"], url: "" },
  "Rogers Wireless": { emails: ["abuse@rogers.com", "phishing@rogers.com"], url: "" },
  "Signal One": { emails: ["admin@soe01.com"], url: "" }
  "SIP.US": { emails: ["abuse@sip.us", "support@mybwc.zendesk.com", "voicesecurity@bandwidth.com"], url: "https://www.bandwidth.com/report-a-phone-number/" },
  "Skype/Level 3": { emails: ["security.feedback@level3.com", "abuse@level3.com"], url: "" },
  "Sonic Systems": { emails: ["psftech@swbell.net", "abuse@swbell.net"], url: "" },
  "Southwestern Bell": { emails: ["abuse@att.net"], url: "" },
  "Sprint Spectrum, L.P.": { emails: ["abuse@sprint.net", "security@sprint.net"], url: "" },
  "TC Systems": { emails: ["support@tctechsystems.com"], url: "" },
  "Telengy L.L.C": { emails: ["info@telengy.net", "lnp@telengy.net", "noc@telengy.net", "legal@telengy.net", "abuse@telengy.net", "support@telengy.net", "sales@telengy.net"], url: "" },
  "Teleport Communications America": { emails: ["info@teleportone.com", "abuse@teleportone.com", "support@teleportone.com"], url: "" },
  "Telnyx": { emails: ["support@telnyx.com"], url: "https://telnyx.com/report-abuse" },
  "TextPlus": { emails: ["support@textplus.com", "lawenforcement@textplusteam.com", "abuse@textplus.com", "bishop@textplus.com"], url: "" },
  "Thinq": { emails: ["noc@thinq.com"], url: "" },
  "T-MOBILE USA INC": { emails: ["abuse@t-mobile.com"], url: "" },
  "TollFreeForwarding.com": { emails: ["support@tollfreeforwarding.com"], url: "" },
  "USA Mobility Wireless, Inc.": { emails: ["customer.care@spok.com"], url: "" },
  "Vonage": { emails: ["abuse@vonage.com", "phishing@vonage.com"], url: "https://www.inteliquent.com/contact-legal/report-abuse" },
  "ZipWhip": { emails: ["supportlist@zipwhip.com", "support@zipwhip.com", "reportabuse@zipwhip.com"], url: "" }
};

